baseURL = 'https://ashoktest.netlify.app'
languageCode = 'en-us'
title = 'Vasuki Parvat'
[params]
  mainSections = ['posts', 'docs', 'blogs']

mobileNavigation = "right" # Mobile nav menu will open to the left of the screen.

numberOfTagsShown = 4
