baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Vasuki Parvat'
[params]
  mainSections = ['posts', 'docs', 'blogs']

mobileNavigation = "left" # Mobile nav menu will open to the left of the screen.

numberOfTagsShown = 4
